name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          npm ci

      - name: Add ES module support
        run: echo '{ "type": "module" }' > package.json && cat package.json >> package.json.bak && mv package.json.bak package.json

      - name: Build project
        run: node ./node_modules/vite/bin/vite.js build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
